name: publish
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      - name: Make Gradle executable
        run: chmod 755 gradlew
      - name: Build
        run: ./gradlew build
      - name: Read Properties
        id: read_properties
        run: cat gradle.properties >> $GITHUB_OUTPUT
      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{format('SimpleClient {0}', steps.read_properties.outputs.simpleclient_version)}}
          artifacts: build/libs/*
          bodyfile: changelog.md
          tag: ${{steps.read_properties.outputs.simpleclient_version}}
          skipIfReleaseExists: true
